FROM ros:melodic

RUN apt-get update -y
RUN apt-get install ros-melodic-rosdoc-lite -y
RUN apt-get install texlive-lang-cjk xdvik-ja evince -y
RUN apt-get install texlive-fonts-recommended texlive-fonts-extra -y
